spring:
  datasource:
    url: jdbc:sqlite:/path/to/turso.db # Replace with actual Turso connection string
jwt:
  secret: "prod-secret-key-change-me" 
plaid:
  environment: production
  client-id: ${PLAID_CLIENT_ID}
  secret: ${PLAID_PRODUCTION_SECRET}
  webhook-url: "http://localhost:8080/api/v1/plaid/webhook" 